default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("DB_POOL", 5) %>
  host: <%= ENV.fetch("DB_HOST", "db_zssn") %>
  port: <%= ENV.fetch("DB_PORT", "5432") %>
  username: <%= ENV.fetch("DB_PRIMARY_USERNAME", "postgres") %>
  password: <%= ENV.fetch("DB_PRIMARY_PASSWORD", "postgres") %>

development:
  <<: *default
  database: zssn_dev

test:
  <<: *default
  database: zssn_test
